export const ROUTE_PATH = {
  home: "/",
  generalne: "/posluhy/generalne-prybyrannya",
  vikna: "/posluhy/myttya-vikon",
  remont: "/posluhy/prybyrannya-pislya-remontu",
  kvartyra: "/posluhy/ekspres-prybyrannya",
  ofis: "/posluhy/prybyrannya-ofisiv",
  mebli: "/posluhy/himchystka-mebliv",
  "article-remont-price": "/blog/skilky-koshtuye-prybyrannya-pislya-remontu",
  "article-ofis-price": "/blog/skilky-koshtuye-klining-ofisu",
  "article-mebli-price": "/blog/skilky-koshtuye-himchystka-dyvana",
  "article-generalne-price": "/blog/skilky-koshtuye-generalne-prybyrannya-50m2",
  "article-generalne-vs-standard": "/blog/generalne-vs-zvychaine-prybyrannya",
  "article-vikna-vysotky": "/blog/myttya-vikon-u-vysotkah",
  "article-kvartyra-vs-generalne": "/blog/ekspres-vs-generalne-prybyrannya",
  "article-generalne-frequency": "/blog/yak-chasto-generalne-prybyrannya",
  "article-generalne-backstage": "/blog/robochyi-den-brygady-chysto",
  "article-vikna-zyma": "/blog/chym-myty-vikna-vzymky",
  "article-vikna-doroga": "/blog/myttya-vikon-bilya-dorogy",
  "article-kvartyra-support": "/blog/yak-pidtrymuvaty-poryadok-mizh-prybyrannyamy",
  "article-kvartyra-2room-price": "/blog/tsina-ekspres-prybyrannya-2k-kvartyry",
  "article-remont-days": "/blog/cherez-skilky-dniv-pislya-remontu-prybyrannya",
  "article-remont-why-expensive": "/blog/chomu-prybyrannya-pislya-remontu-dorozhche",
  "article-ofis-outsource": "/blog/autsorsyng-klining-chy-shtatnyi-prybyralnyk",
  "article-ofis-frequency": "/blog/yak-chasto-prybyraty-ofis",
  "article-mebli-frequency": "/blog/yak-chasto-himchystka-mebliv",
  "article-mebli-carpet-choice": "/blog/himchystka-kylyma-vdoma-chy-v-kompanii",
};

export const PATH_ROUTE = Object.fromEntries(Object.entries(ROUTE_PATH).map(([k,v]) => [v,k]));

export const PAGE_META = {
  home: { title: "Клінінг Миколаїв — прибирання квартир та офісів | чисто.", description: "«чисто.» — клінінгова компанія в Миколаєві. Замовити клінінг: генеральне прибирання, миття вікон, хімчистка меблів. Розрахунок ціни онлайн." },
  generalne: { title: "Генеральне прибирання в Миколаєві від 90 грн/м² | чисто.", description: "Генеральне прибирання квартир і будинків (уборка квартир) — клінінг Миколаїв від «чисто.». Замовити прибирання квартири можна онлайн: чек-лист по кімнатах, розрахунок ціни за хвилину." },
  vikna: { title: "Миття вікон у Миколаєві від 160 грн/м² | чисто.", description: "Клінінг Миколаїв: професійне миття вікон, рам, відкосів. Замовити клінінг вікон можна онлайн — промисловий альпінізм для висоток, розрахунок вартості за хвилину." },
  remont: { title: "Прибирання після ремонту в Миколаєві | чисто.", description: "Прибирання після ремонту — заказать клининг после ремонта (клининг Николаев) від команди «чисто.». Будівельний пил, плівка, розчин, виїзд по області." },
  kvartyra: { title: "Експрес-прибирання квартири в Миколаєві | чисто.", description: "Замовити прибирання квартири швидко (убрать квартиру Николаев) — клінінг Миколаїв за один візит. Розрахунок вартості онлайн, виїзд протягом 1-2 днів." },
  ofis: { title: "Прибирання офісів у Миколаєві | чисто.", description: "Клінінг Миколаїв для бізнесу (клининг Николаев): офіси та комерційні приміщення. Замовити клінінг офісу можна онлайн — гнучкий графік, розрахунок вартості за хвилину." },
  mebli: { title: "Хімчистка меблів у Миколаєві — дивани, килими | чисто.", description: "Клінінг Миколаїв: хімчистка м'яких меблів, килимів, матраців. Замовити клінінг меблів можна онлайн — вартість договірна, залежить від обсягу та забруднення." },
  "article-remont-price": { title: "Ціна прибирання після ремонту 1-к квартири | чисто.", description: "Чому прибирання після ремонту дорожче за звичайне і від чого залежить фінальна ціна. Пояснюємо чесно, без фіксованих цифр навмання." },
  "article-ofis-price": { title: "Скільки коштує клінінг офісу в Миколаєві | чисто.", description: "Як формується ціна клінінгу офісу: разовий виїзд чи контракт, площа, тип покриття, графік роботи." },
  "article-mebli-price": { title: "Скільки коштує хімчистка дивана в Миколаєві | чисто.", description: "Від чого залежить вартість хімчистки м'яких меблів і чому неможливо назвати фіксовану ціну наперед." },
  "article-generalne-price": { title: "Ціна генерального прибирання 50 м² у Миколаєві | чисто.", description: "Чесна відповідь без фіксованих цифр: від чого залежить ціна генерального прибирання 50 м² і чому дві однакові квартири коштують по-різному." },
  "article-generalne-vs-standard": { title: "Генеральне vs звичайне прибирання — в чому різниця | чисто.", description: "Що входить у звичайне прибирання, а що додає генеральне: стелі, техніка зсередини, шви плитки. Як часто потрібне кожне." },
  "article-vikna-vysotky": { title: "Миття вікон у висотках — промисловий альпінізм | чисто.", description: "Коли достатньо звичайного виїзду, а коли для миття вікон потрібен майстер з альпіністським спорядженням." },
  "article-kvartyra-vs-generalne": { title: "Експрес-прибирання vs генеральне — коли що обирати | чисто.", description: "Коли достатньо швидкого прибирання, а коли варто одразу замовляти генеральне. Практичні поради з досвіду." },
  "article-generalne-frequency": { title: "Як часто варто робити генеральне прибирання | чисто.", description: "Скільки разів на рік потрібне генеральне прибирання залежно від тварин, дітей і розташування квартири." },
  "article-generalne-backstage": { title: "Один робочий день бригади «чисто.» зсередини | чисто.", description: "Як насправді проходить виїзд на генеральне прибирання — від підготовки інвентарю до фінальної перевірки." },
  "article-vikna-zyma": { title: "Чим мити вікна взимку, щоб не тріснули | чисто.", description: "Ризик термошоку скла взимку і як правильно мити вікна в мороз без пошкодження склопакетів." },
  "article-vikna-doroga": { title: "Як часто мити вікна в квартирі біля дороги | чисто.", description: "Чому вікна біля траси забруднюються швидше і яка оптимальна частота миття для таких квартир." },
  "article-kvartyra-support": { title: "Як підтримувати порядок між прибираннями | чисто.", description: "Щоденні й щотижневі звички, які тримають квартиру в порядку між генеральними прибираннями." },
  "article-kvartyra-2room-price": { title: "Ціна експрес-прибирання 2-к квартири | чисто.", description: "Скільки коштує швидке прибирання 2-кімнатної квартири і від чого залежить сума." },
  "article-remont-days": { title: "Коли замовляти прибирання після ремонту | чисто.", description: "Оптимальний термін виклику клінерів після ремонту, щоб не переплачувати і не прибирати двічі." },
  "article-remont-why-expensive": { title: "Чому прибирання після ремонту дорожче | чисто.", description: "Пояснюємо різницю в ціні між звичайним генеральним прибиранням і прибиранням після ремонту." },
  "article-ofis-outsource": { title: "Аутсорсинг клінінгу vs штатний прибиральник | чисто.", description: "Порівняння витрат: аутсорсинг клінінгу офісу проти найму штатного прибиральника." },
  "article-ofis-frequency": { title: "Як часто потрібно прибирати офіс | чисто.", description: "Оптимальна частота прибирання офісу залежно від прохідності та розміру команди." },
  "article-mebli-frequency": { title: "Як часто робити хімчистку меблів | чисто.", description: "Рекомендована періодичність хімчистки м'яких меблів для профілактики і догляду." },
  "article-mebli-carpet-choice": { title: "Хімчистка килима вдома чи в пральні | чисто.", description: "Порівняння хімчистки килима на місці та здачі в спеціалізовану пральню — що обрати." },
};
